import InputPartActions from "./message-actions";

export enum BulletNoteActionTypes {
  ADD_MESSAGE = 'ADD_MESSAGE',
  DELETE_MESSAGE = 'DELETE_MESSAGE',
  MOVE_MESSAGE_TO_LATEST = 'MOVE_MESSAGE_TO_LATEST',
  
  SET_MESSAGE_FROM_DB = 'SET_MESSAGE_FROM_DB',

  TOGGLE_MESSAGE_ISDONE = 'TOGGLE_MESSAGE_ISDONE',
  TOGGLE_MESSAGE_ISSTAR = 'TOGGLE_MESSAGE_ISSTAR',
  TOGGLE_MESSAGE_ISPIN = 'TOGGLE_MESSAGE_ISPIN',

  EDIT_MESSAGE = 'EDIT_MESSAGE',
  EDIT_IT = 'EDIT_IT',

  SET_DAYS_RANGE = 'SET_DAYS_RANGE',
}

type BulletNoteActions = InputPartActions

export default BulletNoteActions;